#!/usr/bin/env bash
PMOVDIR=${PMOVDIR:-.}
OUTDIR=${OUTDIR:-$PMOVDIR/pmovie-scan}
mkdir -p $OUTDIR

HASHFILE=${HASHFILE:-$OUTDIR/hash.d}
FIRSTPMOV=$(ls $PMOVDIR/pmovie*.p4* | sort -V | head -n 1)
firsthash.py $FIRSTPMOV $HASHFILE $OUTDIR/orig.npy

