#!/usr/bin/env bash
USAGE="Copies pmovie reading scripts and makes pbs files.

Usage:
    ./pmovie-prep [options] <pmovie-dir> [<pbsoutput-dir> [<lspreader-dir>]]

For <pmovie-dir>, it accepts a valid directory within reach of rcp and rsh.
For example, for /tmp/foo node02 on ramses, specify the path as
\"node02:/tmp/foo\".

Options:
    -h                   Print help
    -s SERVER            Specify server. Current valid ones are \"ramses\" and \"glenn\".
                         \"ramses\" is default.
    -N RAMSESNODE        Run only on the node RAMSESNODE. Usually, the generating
                         pbs script will run on a node specified in the <pmovie-dir>
                         argument.
    -S SCRIPT            Select a scan script. Either it is a file in the current
                         directory or it is a file in lspreader.
    -c CONDAFILE         File to source for conda. This should be a conda with
                         lspreader installed.
    -U                   Expect pmovie files to NOT be gzipped.
"
NODES=1
SERVER="ramses"
RDDIR="/home/ngirmang.1/lspreader"
CONDA="/home/ngirmang.1/conda"
RAMSESNODE=
MYSCANSCRIPT=Escan.py
ZIPPED=--gzip
while getopts ':hS:s:N:c:U' opt; do
      case $opt in
          h)
              echo "$USAGE"
              exit 0
              ;;
          N)
              RAMSESNODE=$OPTARG
              ;;
          s)
              SERVER=$OPTARG
              ;;
          S)
              case $OPTARG in
                  Escan.py)
                      MYSCANSCRIPT=Escan.py
                      ;;
                  Escan-with-region.py)
                      MYSCANSCRIPT=Escan-with-region.py
                      ;;
                  *)
                      MYSCANSCRIPT=
                      THEIRSCANSCRIPT=$OPTARG
                      ;;
              esac
              ;;
          o)
              SCANOPTS=$OPTARG
              ;;
          c)
              CONDA=$OPTARG
              ;;
          \?)
              echo "Invalid option: $OPTARG">&2
              exit 1
              ;;
          :)
              echo "Option -$OPTARG requires an argument.">&2
              exit 1
              ;;
	  U)
              ZIPPED=
              ;;
      esac
done
shift "$((OPTIND-1))"

source $CONDA
DEST=$( [ -n "$1" ] && echo $1)
if [ "$DEST" == "." ]; then DEST=$(pwd); fi;
[ -z "$DEST" ] && echo $USAGE && exit 1;
OUTDIR=$( [ -n "$2" ] && echo $2 ||  echo "." )
[ -n "$3" ]  && RDDIR="$3";

if [ -n "$MYSCANSCRIPT" ]; then
    rcp $RDDIR/pmovie/scan/$MYSCANSCRIPT $DEST/scanner.py
elif [ -n "$THEIRSCANSCRIPT" ] && [ -e "$THEIRSCANSCRIPT" ]; then
    rcp $THEIRSCANSCRIPT $DEST/scanner.py
else
    echo "Didn't find the scan script:" $THEIRSCANSCRIPT
    exit;
fi

#checking for remote node
if [ -n "$( echo "$DEST" | grep \: )" ]; then
    RAMSESNODE=$(echo "$DEST" | sed 's/@\{0,1\}\([A-Z,a-z,0-9]\+\):.*/\1/');
fi
#copying files to the working directory
rcp $RDDIR/pmovie/searchp4.py $RDDIR/pmovie/gather.py \
    $RDDIR/pmovie/traj.py $RDDIR/pmovie/orig.py \
    $RDDIR/pmovie/scanp4.py $RDDIR/bin/pmov.py \
    $DEST
#copying the pmovie-pbsgen.py generator to the directory to make the pbs script
rcp $RDDIR/pmovie/pmovie-pbsgen.py $OUTDIR/
if [ $SERVER == "ramses" ] && [ -n "$RAMSESNODE" ]; then
    DIRONNODE=$(echo "$DEST" | sed 's/@\{0,1\}[A-Z,a-z,0-9]\+:\(.*\)/\1/');
    rsh $RAMSESNODE ls "$DIRONNODE">.lsfiles
    rcp "$DEST/*.lsp" ./.destlsp
    ./pmovie-pbsgen.py --server=$SERVER --nodes=$NODES --outdir=$OUTDIR \
                       --dotlsp=.destlsp --filelist=.lsfiles \
		       $ZIPPED --conda=$CONDA \
                       --ramses-node=$RAMSESNODE $DIRONNODE
else
    ./pmovie-pbsgen.py --server=$SERVER --nodes=$NODES --outdir=$OUTDIR \
                       $ZIPPED --conda=$CONDA \
                       --ramses-node=$RAMSESNODE $DEST
fi

PBSES=$(ls | grep 'pmovie-conv.*.pbs$')
#generating the reader script. Calling it unleashes the hounds.
echo "#!/bin/bash

for i in $PBSES; do
    qsub \$i;
done;
">pmoviereader.sh
chmod +x pmoviereader.sh
